web/router.ex
defmodule Unafrik.Router do
  use Unafrik.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Unafrik.Plug.CurrentUser
  end

  pipeline :required_login do
    plug Guardian.Plug.EnsureAuthenticated,
       handler: Unafrik.GuardianErrorHandler
  end

  pipeline :admin do
    plug :put_layout, {Unafrik.LayoutView, :admin_two}
  end

  scope "/", Unafrik do
    pipe_through [:browser, :with_session] # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create,
                                                   :delete]

    resources "/subscriptions", SubscriptionController, only: [:new, :create]

    get "/contact_us", MessageController, :new
    post "/contact_us", MessageController, :create
  end

  scope "/admin", Unafrik.Admin, as: :admin do
    pipe_through [:browser, :admin, :with_session, :required_login]

    resources "/sessions", SessionController, only: [:new, :create,
                                                   :delete]
    resources "/users", UserController

    get "/", PageController, :index
  end

  # Other scopes may usce custom stacks.
  # scope "/api", Unafrik do
  #   pipe_through :api
  # end
end

web/models/message.ex
defmodule Unafrik.Message do
  use Unafrik.Web, :model

  schema "messages" do
    field :name, :string
    field :email, :string
    field :company_name, :string
    field :message_body, :string
    field :inquiry_type, InquiryTypeEnum, default: 5

    timestamps()
  end

  @required_fields ~w(name email inquiry_type message_body)a
  @optional_fields ~w(company_name)a

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @required_fields ++ @optional_fields)
    |> validate_required(@required_fields)
    |> validate_format(:email, ~r/@/)
  end
end

web/controllers/message_controller.ex
defmodule Unafrik.MessageController do
  use Unafrik.Web, :controller

  alias Unafrik.Message

  def new(conn, _params) do
    changeset = Message.changeset(%Message{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"message" => message_params}) do
    message_params = valide_inquiry_param(message_params)
    changeset = Message.changeset(%Message{}, message_params)

    case Repo.insert(changeset) do
      {:ok, _message} ->
        conn
        |> put_flash(:info, "Message created successfully.")
        |> redirect(to: page_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  defp valide_inquiry_param(params) do
    case {:ok, Map.get(params, "inquiry_type", "")} do
      {:ok, type} ->
        params = Map.put(params, "inquiry_type", String.to_integer(type))
      {:ok, ""} -> params
    end
  end
end

web/views/message_view.ex
defmodule Unafrik.MessageView do
  use Unafrik.Web, :view

  def inquiry_types do
    InquiryTypeEnum.__enum_map__()
    |> Enum.map(fn({k, v}) -> {k, v} end)
  end
end

web/templates/message/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :company_name, class: "control-label" %>
    <%= text_input f, :company_name, class: "form-control" %>
    <%= error_tag f, :company_name %>
  </div>

  <div class="form-group">
    <%= label f, :message_body, class: "control-label" %>
    <%= textarea f, :message_body, class: "form-control" %>
    <%= error_tag f, :message_body %>
  </div>

  <div class="form-group">
    <%= label f, :inquiry_type, class: "control-label" %>
    <%=# number_input f, :inquiry_type, class: "form-control" %>
    <%= select f, :inquiry_type,
                  inquiry_types(),
                  required: true,
                  class: "form-control",
                  prompt: "Select..."
                  %>
    <%= error_tag f, :inquiry_type %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/message/index.html.eex
<h2>Listing messages</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Company name</th>
      <th>Message body</th>
      <th>Inquiry type</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for message <- @messages do %>
    <tr>
      <td><%= message.name %></td>
      <td><%= message.email %></td>
      <td><%= message.company_name %></td>
      <td><%= message.message_body %></td>
      <td><%= message.inquiry_type %></td>

      <td class="text-right">
        <%= link "Show", to: message_path(@conn, :show, message), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: message_path(@conn, :edit, message), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: message_path(@conn, :delete, message), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New message", to: message_path(@conn, :new) %>

web/templates/message/new.html.eex
<h2>New message</h2>

<%= render "form.html", changeset: @changeset,
                        action: message_path(@conn, :create) %>