web/router.ex
defmodule Unafrik.Router do
  use Unafrik.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Unafrik.Plug.CurrentUser
  end

  pipeline :required_login do
    plug Guardian.Plug.EnsureAuthenticated,
       handler: Unafrik.GuardianErrorHandler
  end

  pipeline :admin do
    plug :put_layout, {Unafrik.LayoutView, :admin_two}
  end

  scope "/", Unafrik do
    pipe_through [:browser, :with_session] # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create,
                                                   :delete]

    resources "/subscriptions", SubscriptionController, only: [:new, :create]

    get "/contact_us", MessageController, :new
    post "/contact_us", MessageController, :create
  end

  scope "/admin", Unafrik.Admin, as: :admin do
    pipe_through [:browser, :admin, :with_session, :required_login]

    resources "/sessions", SessionController, only: [:new, :create,
                                                   :delete]
    resources "/users", UserController

    get "/", PageController, :index
  end

  # Other scopes may usce custom stacks.
  # scope "/api", Unafrik do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Unafrik.LayoutView do
  use Unafrik.Web, :view
end

web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin::Unafrik</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/admin_semantic.css") %>">
  </head>

  <body>
    <header class="cd-main-header">
  		<a href="#0" class="cd-logo"><img src="<%= static_path(@conn, "/images/cd-logo.svg") %>" alt="Logo"></a>

  		<%# <div class="cd-search is-hidden"> %>
  			<%# <form action="#0">
  				<input type="search" placeholder="Search...">
  			</form> %>
  		<%# </div> <!-- cd-search --> %>

  		<a href="#0" class="cd-nav-trigger">Menu<span></span></a>

  		<nav class="cd-nav">
  			<ul class="cd-top-nav">
  		<%# 		<li><a href="#0">Tour</a></li>
  				<li><a href="#0">Support</a></li> %>
  				<li class="has-children account">
  					<a href="#0">
  						<img src="<%= static_path(@conn, "/images/cd-avatar.png") %>" alt="avatar">
  						Account
  					</a>

  					<ul>

  						<li>
                <%= link "My Account", to: admin_user_path(@conn, :index) %>
              </li>

  						<li>
                <%= link "Edit Account", to: admin_user_path(@conn, :edit, @current_user) %>
              </li>

              <li>
                <%= link "Logout", to: session_path(Unafrik.Endpoint, :delete, @current_user), method: "delete" %>
              </li>

              <li>
                <%= link "Logout 2", to: admin_session_path(@conn, :delete, @current_user), method: "delete" %>
              </li>

              <li>
                <%= link "Logout 3", to: admin_session_path(Unafrik.Endpoint, :delete, @current_user), method: "delete" %>
              </li>

  					</ul>
  				</li>
  			</ul>
  		</nav>
  	</header> <!-- .cd-main-header -->

    <main class="cd-main-content">
  		<nav class="cd-side-nav">
  			<ul>
  				<li class="cd-label">Main</li>
          <li class="has-children overview">
            <a href="#0">Overview</a>

            <ul>
              <li><a href="#0">All Data</a></li>
              <li><a href="#0">Category 1</a></li>
              <li><a href="#0">Category 2</a></li>
            </ul>
          </li>
          <li class="has-children notifications active">
            <a href="#0">Notifications<span class="count">3</span></a>

            <ul>
              <li><a href="#0">All Notifications</a></li>
              <li><a href="#0">Friends</a></li>
              <li><a href="#0">Other</a></li>
            </ul>
          </li>
          <li class="has-children comments">
            <a href="#0">Comments</a>

            <ul>
              <li><a href="#0">All Comments</a></li>
              <li><a href="#0">Edit Comment</a></li>
              <li><a href="#0">Delete Comment</a></li>
            </ul>
          </li>
        </ul>

        <ul>
          <li class="cd-label">Secondary</li>
          <li class="has-children bookmarks">
            <a href="#0">Bookmarks</a>

            <ul>
              <li><a href="#0">All Bookmarks</a></li>
              <li><a href="#0">Edit Bookmark</a></li>
              <li><a href="#0">Import Bookmark</a></li>
            </ul>
          </li>
          <li class="has-children images">
            <a href="#0">Images</a>

            <ul>
              <li><a href="#0">All Images</a></li>
              <li><a href="#0">Edit Image</a></li>
            </ul>
          </li>

          <li class="has-children users">
            <a href="#0">Users</a>

            <ul>
              <li>
                <%= link "All Users", to: admin_user_path(@conn, :index) %>
              </li>
              <li>
                <%= link "Edit User", to: admin_user_path(@conn, :edit, @current_user) %>
              </li>
              <li>
                <%= link "New User", to: admin_user_path(@conn, :new) %>
              </li>
            </ul>
          </li>
        </ul>

        <ul>
          <li class="cd-label">Action</li>
          <li class="action-btn"><a href="#0">+ Button</a></li>
        </ul>
      </nav>

      <div class="content-wrapper">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

        <%= render @view_module, @view_template, assigns %>
      </div>
    </main> <!-- .content-wrapper -->

    <footer role="contentinfo">
      <div class="site-info">
        <div class="about-section">
        </div>
      </div>
    </footer>

    <script src="<%= static_path(@conn, "/js/admin_semantic.js") %>"></script>
  </body>
</html>

web/templates/layout/admin_two.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Unafrik!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/admin_two.css") %>">
  </head>

  <body>
    <header class="header">
      <div class="header__logo-container">
        <a href="#"><img class="header__logo-container-logo" src="#/img/tb_bug@2x.png"></a>
        <a href="#"><span class="header__logo-container-description">Account</span></a>
      </div>

      <div id="" class="header__nav">
        <div class="header__nav-body">
          <i class="header-icon header-user-icon"></i>
          <span class="header-title">Gilbert Ekoue
            <i class="header-icon header-nav-arrow-down"></i>
          </span>

          <ul class="header-menu">
            <li>
              <a href="#userSettings">Profile</a>
            </li>
            <li>
              <a href="#logout">Logout</a>
            </li>
          </ul>
        </div>
      </div>

      <div id="" class="header__nav">
        <div class="header__nav-body">
          <i class="header-icon header-question-mark"></i>
          <span class="header-title">Help
            <i class="header-icon header-nav-arrow-down"></i>
          </span>
        </div>
      </div>

      <div id="" class="header__nav">
        <div class="header__nav-body">
          <i class="header-icon header-dev-center"></i>
          <a href="#developer">
            <span class="header-title header-top-nav-padding">Developer Center</span>
          </a>
        </div>
      </div>
    </header>

    <ul id="ac-side-navs">
      <div id="">
        <li class="ac-side-nav">
          <a href="#" class="">
            <i class="ac-icon ac-overview"></i>
            <span>Account Overview</span>
          </a>
        </li>
      <div class="ac-nav-no-projects">
        <div class="ac-header">
          <i class="ac-icon ac-embed"></i>
          <span>0 VIDEO CHAT EMBEDS</span>
        </div>

        <div class="ac-body">
          Quickly generate some code
                      to embed in your website
                      (basic features +  web only)
        </div>

        <div class="ac-body">
          <button class="ac-action-standard ac-btn-green-ghost">
            <i class="ac-icon ac-add-icon"></i>
            <span>Create embed</span>
          </button>
        </div>
      </div>
      <li class="ac-projects-nav ac-side-nav active">
        <a class="active-link">
          <i class="ac-icon ac-project-white"></i>
          <span class="ac-nav-label ac-size8 ac-color-grey2">PROJECT</span>
          <span class="ac-overflow-ellipsis">ALLO</span>
          <i class="ac-icon ac-small-arrow-right-white"></i>
        </a>
      </li>
    </div>
    <li class="ac-side-nav">
      <a href="#settings" class="">
        <i class="ac-icon ac-settings"></i>
        <span>Account Settings</span>
      </a>
    </li>
    <div id="ac-side-nav-upgrade">
      <strong> YOU ARE IN TRIAL MODE</strong>
      <button class="ac-btn-standard ac-btn-blue-fill ac-left-upgrade">
        Upgrade now
      </button>
    </div>

    <div>
      <div id="ac-side-nav-legal-container" class="ac-size10">
        <a id="ac-privacy-policy" href="#https://tokbox.com/support/privacy-policy" target="_blank">
          Privacy Policy
        </a>
        <span>|</span>
        <a id="ac-terms-of-service" href="https://tokbox.com/support/tos" target="_blank">
          Terms of Service
        </a>
      </div>
    </div>
  </ul>


    <div id="ac-content">
      <div class="animated fadeIn">
        <div id="ac-account-overview-header" class="ac-section ac-section-blue ac-section-padding">
          <div class="ac-section-header">
            <div class="ac-row">
              <div class="ac-column ac-c-20">
                <span class="ac-size32 ac-capitalize ac-overflow-ellipsis ">
                  Teladoc
                </span>
              </div>

              <div class="ac-column ac-c-80 ac-right-align">
                <span class="ac-size14 ac-margin-right ac-fade">RUNNING TRIAL</span>
                <span class="ac-size24">$</span>
                <span class="ac-size32">0</span>
              </div>
            </div>
          </div>

          <div class="ac-section-body">
            <div class="ac-row">
              <div class="ac-column ac-c-80 ac-right-align ac-offset-20">
                <div class="ac-usage-overview">
                  <i class="ac-icon ac-project-minutes"></i>
                  <span class="ac-fade ac-size12">SUBSCRIBED MIN.</span>
                  <div class="ac-value ac-left-align">
                    <span class="ac-size14">$</span>
                    <span class="ac-size20">0</span>
                  </div>
                </div>

                <div class="ac-usage-overview">
                  <i class="ac-icon ac-project-archiving"></i>
                  <span class="ac-fade ac-size12">ARCHIVED MIN</span>
                  <div class="ac-value ac-left-align">
                    <span class="ac-size14">$</span>
                    <span class="ac-size20">0</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div id="ac-trial-container">
          <div id="ac-trial-counter" style="position: relative;">
            <svg viewBox="0 0 100 100" style="display: block; width: 100%;">
              <path d="M 50,50 m 0,-45 a 45,45 0 1 1 0,90 a 45,45 0 1 1 0,-90" stroke="#0099CC" stroke-width="9" fill-opacity="0"></path>
              <path d="M 50,50 m 0,-45 a 45,45 0 1 1 0,90 a 45,45 0 1 1 0,-90" stroke="#dbe4e8" stroke-width="10" fill-opacity="0" style="stroke-dasharray: 282.783, 282.783; stroke-dashoffset: 222.187;"></path>
            </svg>
            <p class="ac-counter-label " style="color: rgb(0, 0, 0); position: absolute; left: 50%; top: 50%; padding: 0px; margin: 0px; transform: translate(-50%, -50%);">22</p>
          </div>

          <div class="ac-trial-body">
            <div class="ac-row">
              <div class="ac-column ac-c-75">
                <span class="ac-label-grey5 ac-size15 ac-label">You are currently in the trial period</span>
                <p>Upgrade to a paid account to continue using TokBox after your trial expires.</p>
              </div>

              <div class="ac-column ac-c-25">
                <button class="ac-btn-standard ac-btn-blue-fill ac-left-upgrade">
                   Upgrade now
                 </button>
               </div>
             </div>
           </div>
         </div>

         <div id="ac-account-no-project-overview" class="ac-section-with-header">
           <div class="ac-section-header">
             <span>Get Started</span>
           </div>

           <div class="ac-section-body">
             <div class="ac-row ac-padding-bottom-2x">
               <div class="ac-column ac-c-20 ac-left-align">
                 <img src="./img/embed_icon-big.svg" width="85">
               </div><div class="ac-column ac-c-80">
                 <span class="ac-label-grey5 ac-size15 ac-label">Create a video chat embed</span>
                 <p>Start with generated code for quick implementation into your existing website.
                   We recommend test projects for proofs-of-concept, small-scale testing, and other
                   lightweight use cases - not for full-scale production.
                   (Audio and video features, web only)
                 </p>

                 <div class="row ac-right-align">
                   <button class="ac-btn-small ac-btn-green-fill">Create embed</button>
                 </div>
               </div>
             </div>

             <div class="ac-row">
               <div class="ac-column ac-c-20 ac-left-align">
                 <img src="./img/project_banner@2x.png" width="85">
               </div>

               <div class="ac-column ac-c-80">
                 <span class="ac-label-grey5 ac-size15 ac-label">Create a project</span>
                 <p>
                   Projects allow for maximum customization, access to all features
                   (including archiving, screensharing, monitoring configuration,
                   and more), web and mobile interoperability, and production-ready
                   scalability. When you create a new projects, you will get an
                   API Key and Secret, allowing your application to communicate with
                   the OpenTok platform.
                 </p>

                 <div class="row ac-right-align">
                   <button class="ac-btn-small ac-btn-green-fill">Create project</button>
                 </div>
               </div>
             </div>
           </div>

           <div class="ac-section-footer">
           </div>
         </div>
       </div>
     </div>
    <script src="<%= static_path(@conn, "/js/admin.js") %>"></script>
  </body>
</html>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Unafrik!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">

        <span class="logo"></span>

        <nav role="navigation">
          <ol class="breadcrumb text-right">
            <%= if @current_user do %>
              <li>
                <%= @current_user.email %> (<%= @current_user.id %>)
              </li>

              <li>
                <%= link "Sign out", to: session_path(@conn, :delete,
                                         @current_user), method: "delete" %>
              </li>
            <% else %>
              <li><%= link "Register", to: user_path(@conn, :new) %></li>
              <li><%= link "Sign in", to: session_path(@conn, :new) %></li>
            <% end %>
          </ol>
        </nav>

      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->

    <footer role="contentinfo">
      <div class="site-info">
        <div class="about-section">

        </div>

        <section class="social-section">
          <div class="footer-social">
            <ul class="footer-socials">
              <li>
                <a href="javascript:void(0)">
                  <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png" alt="Facebook">
                </a>
              </li>

              <li>
                <a href="javascript:void(0)">
                  <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png" alt="Twitter">
                </a>
              </li>

              <li>
                <a href="javascript:void(0)">
                  <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/youtube-logo-circle.png" alt="YouTube">
                </a>
              </li>
            </ul>
          </div>
        </section>
      </div>

      <div class="copyright">
        @copy 2017 Unafrik
      </div>
    </footer>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/email.html.eex
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Unafrik Email</title>
<link media="all" rel="stylesheet" href="<%= static_url(Unafrik.Endpoint, "/css/email.css") %>">
</head>

<body itemscope itemtype="http://schema.org/EmailMessage">

<table class="body-wrap">
  <tr>
    <td></td>
    <td class="container" width="600">
      <div class="content">
        <table class="main" width="100%" cellpadding="0" cellspacing="0" itemprop="action" itemscope itemtype="http://schema.org/ConfirmAction">
          <tr>
            <td class="content-wrap">
              <meta itemprop="name" content="Confirm Email"/>
              <table width="100%" cellpadding="0" cellspacing="0">
                <%= render @view_module, @view_template, assigns %>
              </table>
            </td>
          </tr>
        </table>
        <div class="footer">
          <table width="100%">
            <tr>
              <td class="aligncenter content-block">Follow <a href="http://twitter.com/unafrik">@Unafrik</a> on Twitter.</td>
            </tr>
          </table>
        </div></div>
    </td>
    <td></td>
  </tr>
</table>

</body>
</html>